version: '3.8'
services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=db;Port=5432;Username=postgres;Password=postgres;Database=authdb
    depends_on:
      - db

  journal-service:
    build:
      context: ./journal-service
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=db;Port=5432;Username=postgres;Password=postgres;Database=journaldb
    depends_on:
      - db

  tree-service:
    build:
      context: ./tree-service
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=db;Port=5432;Username=postgres;Password=postgres;Database=treesdb
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: